os:
  - linux
  - osx
language: rust
cache: cargo # cache cargo-audit once installed
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y libxcb-shape0-dev libxcb-xfixes0-dev; fi
before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile
script:
  - cargo test
  - cargo build --features=fail-on-warnings
  - cargo audit
