language: rust
cache: cargo # cache cargo-audit once installed
before_install:
  - sudo apt-get install -y libxcb-shape0-dev
  - sudo apt-get install -y libxcb-xfixes0-dev
before_script:
  - cargo install --force cargo-audit
  - cargo generate-lockfile
script:
  - cargo test
  - cargo build --features=fail-on-warnings
  - cargo audit
